# sudo docker run --hostname zookeeper1 --restart always -v /home/lmedina/stuff/docker/zookeeper/logs:/var/log/zookeeper
# -v /home/lmedina/stuff/docker/zookeeper/conf:/opt/zookeeper/3.4.6/conf -v /home/lmedina/stuff/docker/zookeeper/files/myid1:/zookeeper/data/myid
# --ulimit nofile=65536:65536 --name zoo -it zookeeper_zookeeper1

zookeeper:
  image: lu4nm3/zookeeper:latest
  hostname: zookeeper
  name: zookeeper
  restart: always
  volumes:
    - /var/log/zookeeper:/var/log/zookeeper
    - ./conf:/opt/zookeeper/3.4.6/conf
    - /zookeeper/data:/zookeeper/data
    - /zookeeper/log:/zookeeper/log
