zookeeper1:
  build: .
  # image: lmedina/zookeeper
  # environment:
  #   - ZOO_LOG_DIR=/var/log/zookeeper
  #   - ZOO_LOG4J_PROP='INFO,ROLLINGFILE'
  # build: .  
  hostname: zookeeper1
  restart: always
  # user: zookeeper
  volumes:
    - ./logs:/var/log/zookeeper
    - ./conf:/opt/zookeeper/3.4.6/conf
    - ./files/myid1:/zookeeper/data/myid