# sudo docker run --hostname zookeeper1 --restart always -v /home/lmedina/stuff/docker/zookeeper/logs:/var/log/zookeeper
# -v /home/lmedina/stuff/docker/zookeeper/conf:/opt/zookeeper/3.4.6/conf -v /home/lmedina/stuff/docker/zookeeper/files/myid1:/zookeeper/data/myid
# --ulimit nofile=65536:65536 --name zoo -it zookeeper_zookeeper1

zookeeper1:
  build: .
  hostname: zookeeper1
  name: zoo1
  restart: always
  volumes:
    - ./logs:/var/log/zookeeper
    - ./conf:/opt/zookeeper/3.4.6/conf
    - ./files/myid1:/zookeeper/data/myid